tus/tus-node-server

README.md
See https://github.com/tus/tus-node-server/issues/16
=> Document how to deploy the server as middleware

lib/stores/FileStore.js
=> Depend on offset value for the total uploaded file size, not new_offset.

lib/handlers/BaseHandler.js, lib/handlers/HeadHandler.js, lib/handlers/PatchHandler.js, lib/handlers/PostHandler.js
Basically changed the regex to match on req.originalUrl instead of req.url
and added req.baseUrl to creation Location to get correct URL.
=> Add support for using tus on an express router

package.json
=> upgrade package dependencies

lib/Server.js, lib/handlers/HeadHandler.js, lib/handlers/PatchHandler.js, lib/handlers/PostHandler.js, lib/stores/DataStore.js, lib/stores/FileStore.js, lib/stores/GCSDataStore.js, package-lock.json, package.json
=> Replaced console.[log|info|warn|error] statements with debug statements

index.d.ts
I add typescript module "index.d.ts" to be compatible with TS.
It's not only can use JS but also can use TS.
I already applied it to my project.
please watch my PR.
=> add typescript

.travis.yml, README.md, package-lock.json, package.json
Fix `npm outdate` and `npm audit`.
Update `dependencies` and `devDependencies`
=> fix/update: dependencies

index.d.ts
Related to issue https://github.com/tus/tus-node-server/issues/228
=> Add region to S3StoreOptions Typescript definition

index.d.ts
=> Fix: solve relativeLocation with wrong type definition

lib/stores/DataStore.js, lib/stores/FileStore.js, test/Test-DataStore.js, test/Test-Stores.shared.js
This PR solves issue reported in #260.
=> announce to client that FileStore supports termination extension

.github/workflows/ci.yml
Unfortunately, #267 and #268 didn't fix it. Another attempt.
=> Try to fix GH Actions for PRs from forks again

demo/server.js, lib/Server.ts, test/Test-EndToEnd.ts, test/Test-Server.ts
=> Make datastore a constructor option

lib/stores/FileStore.ts
=> Fix log in `write` method of `FileStore`

packages/server/src/handlers/BaseHandler.ts, packages/server/src/handlers/GetHandler.ts, packages/server/test/BaseHandler.test.ts
=> @tus/server: improve `getFileIdFromRequest`

packages/server/src/constants.ts, packages/server/src/handlers/BaseHandler.ts, packages/server/test/PostHandler.test.ts
=> @tus/server: fix casing in forwarded headers

packages/s3-store/index.ts
An additional error code to look for the file not found error.
=> @tus/s3-store: add missing error code in termination extension

packages/server/src/handlers/HeadHandler.ts
https://tus.io/protocols/resumable-upload.html#:~:text=MUST%20be%20omitted.-,Upload%2DMetadata,-The%20Upload%2DMetadata
=> Update incorrect comment

packages/server/src/handlers/BaseHandler.ts
=> @tus/server: use Buffer.byteLength for Content-Length

packages/server/src/handlers/PostHandler.ts, packages/server/test/PostHandler.test.ts
=> @tus/server: call onUploadFinish in POST handler for empty files

packages/s3-store/README.md, packages/s3-store/index.ts, packages/s3-store/package.json, packages/s3-store/test.ts, yarn.lock
=> @tus/s3-store: migrate to V3 SDK

packages/server/README.md, packages/server/src/server.ts, packages/server/src/types.ts, packages/server/test/Server.test.ts
=> @tus/server: introduce onIncomingRequest middleware

packages/s3-store/index.ts
Fixes #458 
This was a bit odd, instead of creating an `.info` file with the upload inside the file, we used to create an empty file and put everything on metadata, which the SDK sends alongs has query parameters. Sending an entire JSON string in a header is error-prone and caused issues. What's also odd, is that in `create` we put everything on metedata too but we _also_ call `saveMetadata`, which already does the job.
Now we actually create a file with contents, and only use metadata for `upload-id` and `tus-version`.
=> @tus/s3-store: fix invalid character errors for "x-amz-meta-file” header

packages/s3-store/index.ts, packages/s3-store/test.ts
This PR solves scenario when client chunk size was less then 5MB, which caused data to be written as incomplete part. But when that incomplete part grew beyond 5MB it was not "promoted" to part of multipart upload but kept growing. This meant that amount of data being downloaded and re-uploaded was growing until upload was complete. 
This behavior was only possible since #493, before this scenario wound not work.
=> @tus/s3-store: Upload as multipart upload when incomplete part grows beyond minimal part size

packages/file-store/configstores/FileConfigstore.ts, packages/file-store/test.ts, test/stores.test.ts
=> @tus/file-store: fix list method of FileConfigstore

.github/workflows/ci.yml
=> Run 18x and 21x as Node versions in CI

packages/server/src/handlers/PatchHandler.ts
=> @tus/server: restore the onIncomingRequest callback for PATCH handler.

packages/server/README.md
Just makes it easier to copy paste, the way I like developing 🫢
=> @tus/server: fix typo in readme example code

packages/file-store/README.md, packages/s3-store/README.md, packages/s3-store/index.ts, packages/server/README.md
Ref: #552 
- Export `MetadataValue` so it can be used.
- Document KV stores
=> Document KV stores

.changeset/serious-mangos-wait.md, packages/server/src/server.ts, packages/server/src/types.ts
=> @tus/server: add `lockDrainTimeout` option

.changeset/four-owls-juggle.md, .eslintrc.js, package-lock.json, packages/server/README.md, packages/server/package.json, packages/server/src/handlers/BaseHandler.ts, packages/server/src/handlers/PatchHandler.ts, packages/server/src/handlers/PostHandler.ts, packages/server/src/server.ts, packages/server/src/types.ts, packages/server/test/Server.test.ts, packages/utils/src/constants.ts
=> @tus/server: introduce `POST_RECEIVE_V2`

.changeset/swift-pumpkins-type.md, packages/file-store/package.json, packages/gcs-store/package.json, packages/s3-store/package.json, packages/server/package.json, packages/utils/package.json, tsconfig.base.json
=> Enable declarationMap and sourceMap for TS

.changeset/brave-doors-ring.md, packages/server/src/handlers/OptionsHandler.ts, packages/server/test/OptionsHandler.test.ts
=> @tus/server: send Tus-Version in OPTIONS

.changeset/friendly-panthers-know.md, test/tsconfig.json, tsconfig.json
=> Fix tsconfig to also build @tus/azure
