- lib/constants.js
- lib/handlers/HeadHandler.js
- lib/handlers/PatchHandler.js
- lib/handlers/PostHandler.js
- lib/stores/DataStore.js
- lib/stores/FileStore.js
Starting point for consolidating error handling. The `catch` parts of each handler could be more DRY.
Closes #31
> Use constants for errors

- lib/handlers/PostHandler.js
Removes `http://` prefix from POST handler response
Fixes #48
> Remove HTTP as part of POST handler response

- package.json
Allows node versions `>=6.0`. When using the `yarn` package manager, it does not allow installation since at the moment tus requires _exactly_ the version 6.0.
This should also be pushed to `npm` since on there the engine version is stuck at `4.4.4`.
> Allow node versions >=6.0

- README.md
- demo/server.js
- lib/handlers/BaseHandler.js
- lib/handlers/PostHandler.js
When I wanted to use express app for uploading:
```
const uploadApp = express();
uploadApp.all('*', server.handle.bind(server));
mainApp.use('/uploads', uploadApp);
```
it didn't work because generation of patch url was based on filestorage.path which IMHO should not have had nothing to do with url prefix of incomming request.
PS: usage of express would make much more easy even the rest of the app ;) What do you think?
> patch url generation fix

- lib/validators/RequestValidator.js
fixes https://github.com/tus/tus-node-server/issues/98
---
According to @Acconut (https://github.com/tus/tus-js-client/issues/106#issuecomment-377223525), 0 bytes files should be handled directly in the `POST` (creation of a file) request.
In order to solve this, this pull request unblocks a file size of 0 bytes (`non-negative integer`).
The check if a file has 0 bytes will happen in every DataStores itself (within the `create` method).
I think updating current DataStores can be done in different pull requests.
> Enable 0 byte files

- lib/constants.js
- lib/validators/RequestValidator.js
- test/Test-RequestValidator.js
This will allow requests with `Authorization` present on their headers.
> Allow `Authorization` header. Closes #99

- index.js
In advance of extracting individual datastore packages, export the error constants from the package to facilitate custom datastore creation more cleanly.
> Export Error Constants

- package-lock.json
- package.json
Resolves #119 
This PR is a set of commits which remove or update dependencies in order to eliminate dependence on outdated versions of `stringstream@0.0.5` and `base64url@2.0.0` which both have reported vulnerabilities.
- Updates outdated google-cloud/storage version from 1.1.1 to 1.7.0
- Updates request from ^2.8.5 to 2.8.7 and removes request from the list of direct dependencies as it's never used directly. 
Updating request to 2.87 removes the dependency on stringstream@0.0.5 which has a medium severity security vulnerability. https://snyk.io/vuln/npm:stringstream:20180511
- Removes unused package google-auto-auth@0.8.2. This package was listed as a direct dependency, but is not used in the package directly. This package is a dependency of `@google-cloud/storage` but since updating …
> Resolve dependency vulnerabilities in stringstream and base64url

- lib/handlers/PostHandler.js
- test/Test-EndToEnd.js
hey, thanks for #128 
with `relativeLocation: true` the returned location is only `{uuid}`
it should return the same url just without scheme + host
with patch applied:
`relativeLocation: false` => `//localhost/tus/files/{uuid}`
`relativeLocation: true` => `/tus/files/{uuid}`
> fix relative location url

- .travis.yml
- package-lock.json
- package.json
`dot-prop@4.2.0`, which is installed into `tus-node-server` by `configstore`, shows a medium severity security flag in our snyk tests.
This PR updates `configstore` to v5, which includes an update of `dot-prop`.
> chore: update dependency with security issue

- README.md
- lib/stores/GCSDataStore.js
- test/Test-GCSDataStore.js
My solution is to write to temporary file on subsequent writes and combine with original file. Temporary file is discarded immediately after write.  
I added test for this behavior and improved some other test. Many tests did not remove files after.
Resolves https://github.com/tus/tus-node-server/issues/37
> resumable uploads with GCS 

- lib/handlers/PostHandler.js
- lib/stores/FileStore.js
- lib/stores/GCSDataStore.js
- lib/stores/S3Store.js
- test/Test-EndToEnd.js
When `Content-Type: application/offset+octet-stream` header is present also start upload. I did not want to start file upload when there is no `Content-Type` header as is implemented in goloang, beause that would make additional requests to store (GCS, S3, ...) also in requests when there is no data to upload.
> implementation of creation-with-upload extention

- index.js
- lib/models/Metadata.js
- test/Test-Metadata.js
Metadata is part of a standard and stores might or might not use it. I think that parsing and stringification should be implemented as part of this library (and properly test) even though it is not directly used as metadata is usually just stored in it's encoded form.
I use naming convention from `JSON.parse` and `JSON.stringify`. `Metadata.encode` and `Metadata.decode` can also be used.
> Add metadata parsing and stringification functions

- index.d.ts
* Add Metadata
* Add typed return type to FileStore.getOffset
* Remove duplicated inherited methods from child stores that don't change the types they inherit from DataStore
* Make req parameter type on DataStore.create Partial
* Run through prettier for more standard formatting
> Add Metadata to types and run it through prettier

- index.d.ts
Updates the type of the `Server.get` `callback` parameter to explicitly set its `...args` parameter as `any[]`.
Otherwise, with `noImplicitAny` set in tsconfig, tsc will complain about the implicit `any` type.
> index.d.ts: explicitly type Server.get callback parameter signature

- lib/constants.js
- lib/handlers/PostHandler.js
- lib/stores/DataStore.js
- lib/validators/RequestValidator.js
- test/Test-PostHandler.js
- test/Test-RequestValidator.js
Server returns error 400 and obvious error message if client wants to use concatenation extension when it is not supported.
> Reject partial upload if concatenation extension is not supported

- .github/workflows/ci.yml
- .gitignore
Can't run tests from contributors if we don't have the secret to decrypt the Google Cloud Storage credentials.
However, this comes with security problems: https://securitylab.github.com/research/github-actions-preventing-pwn-requests. You can do two things, make sure the tests only run when a label is added with someone with write permission, or change repository settings to always require manual approval for running actions for outside contributors. I went with the latter.
> GitHub Actions: allow PRs from forks to run with secrets

- lib/stores/GCSDataStore.js
- lib/stores/S3Store.js
- test/Test-Stores.shared.js
Errors in S3 store are not throw correctly. `PostHandler` can properly handle errors that have `status_code` properties. If error object is encapsulated in `Error` class then such error can not be properly handled.
This PR also fixes some tests that did not work at all.
> Correctly throw error in S3 store and check for file ID in GCSDataStore

- lib/stores/S3Store.js
- test/Test-Stores.shared.js
Fix broken upload with deferred length or without metadata using S3 datastore. This fix is already in #186. This PR will allow us to merge this sooner.
> S3Store: fix broken upload with deferred length or without metadata

- lib/models/StreamSplitter.js
- lib/stores/S3Store.js
This PR fixes issue when uploading parts that are smaller than 5MB by ignoring them. Current implementation would upload such parts which would cause the upload to fail at the end when multipart upload is finished and S3 would reject such request.
This PR "fixes" two scenarios. 
First is when uploading chucks smaller than 5MB. Now all chunks are rejected and upload will never complete. Not sure if this is any better then error at the end :smile: 
Second is when chunks are larger than 5MB. Such upload are split to temporary files as specified in S3Store option `options.partSize` with default value of 8MB. Uploaded chunk is split into 8MB parts and a leftover part, this last part can be too small (<5MB) to be accepted by S3. This PR discards this part and signals client that it should be …
> Fix too small parts with S3 datastore

- lib/stores/GCSDataStore.js
Handle insufficient access error by ignoring it.
Fixes https://github.com/tus/tus-node-server/issues/293
> GCS: ignore insufficient access error

- lib/stores/S3Store.js
Digital Ocean Spaces (S3 compatible object storage) sends the upload id information in metadata as `upload-id` instead `upload_id`, so the `_getMetadata` method of `S3Store` returns an empty upload id.
This change is a simple patch that works as a fallback to `upload-id` if `upload_id` is not found.
> Fix upload ID when using S3 store with Digital Ocean Spaces

- .github/workflows/ci.yml
There seems to be a race condition which causes GCS tests to fail. Disabling parallel jobs may fix this.
> Do not run GitHub Actions in parallel

- index.d.ts
- lib/Server.js
- lib/constants.js
- lib/handlers/HeadHandler.js
- lib/handlers/PatchHandler.js
- lib/stores/DataStore.js
- lib/stores/FileStore.js
- lib/stores/GCSDataStore.js
- lib/stores/S3Store.js
- test/Test-EndToEnd.js
- test/Test-FileStore.js
- test/Test-GCSDataStore.js
- test/Test-PatchHandler.js
- test/Test-PostHandler.js
- test/Test-S3DataStore.js
- test/Test-Server.js
- test/Test-Stores.shared.js
> Fix creation-defer-length extension for all stores

- lib/stores/GCSDataStore.js
When the bucket exists then `error` is `null` which causes this code to fail with an error  `TypeError: Cannot read properties of null (reading 'code')`.
We are using `"@google-cloud/storage": "^6.5.2",` but there's no harm in checking if a variable is not null before trying to access a property.
This is with the latest `"tus-node-server": "^0.8.0",` release
> Fix issue where there is no error checking bucket exists in GCSDataStore

- lib/handlers/PatchHandler.js
- lib/handlers/PostHandler.js
- test/Test-PostHandler.js
Event `EVENTS.EVENT_UPLOAD_COMPLETE` is not emitted when upload is completed using `creation-with-upload` extension.
> Emit upload complete event when using creation-with-upload extension

- package-lock.json
- package.json
Reverts tus/tus-node-server#289
This upgrade broke `npm run demo`. Problem is that `tus-js-client` 3.0.0 does not install demo folder anymore which is served by our `demo` command.
> Revert "Bump tus-js-client from 2.3.1 to 3.0.0"

- lib/constants.js
- lib/handlers/PatchHandler.js
- lib/handlers/PostHandler.js
- lib/stores/DataStore.js
- test/Test-EndToEnd.js
- test/Test-PatchHandler.js
- test/Test-PostHandler.js
- test/Test-Server.js
I made a mistake in #297 thinking that either `Upload-Length` or `Upload-Defer-Length` headers MUST be present. This PR fixes this.
We don't need to validate `Upload-Defer-Length` as it is not expected to be present. `Upload-Length` can ONLY be present if extension is supported, and upload length is not yet known.
> fix validation of upload-length header in patch handler

- README.md
Some linters (or personal preference) remove `async` from functions if there are no `await` or return a `Promise` object. This, with some bad errors management in Fastify, has lead me to two full week of head banging. With the sync signature, it gets more explicit that the body parsing always succeed by doing nothing.
Note: `null` is needed due to how Typescript types are defined, for regular Javascript just calling `done()` should works.
> Clarify example for Fastify

- lib/handlers/GetHandler.ts
- lib/handlers/HeadHandler.ts
- lib/handlers/PatchHandler.ts
- lib/stores/DataStore.ts
- lib/stores/FileStore.ts
- lib/stores/GCSDataStore.ts
- lib/stores/S3Store.ts
- test/Test-DataStore.ts
- test/Test-FileStore.ts
- test/Test-GetHandler.ts
- test/Test-HeadHandler.ts
- test/Test-PatchHandler.ts
- test/Test-Stores.shared.ts
`getOffset` implies returning a number, the offset. Instead we return more information so `getUpload` seems better suited and aligned with `tusd`.
Do we want to rename the keys of the return value, and the `File` model too? From:
```ts
id: string
upload_defer_length?: string
upload_metadata?: string
upload_length?: string
size?: number
```
To:
```ts
id: string
isDeferred?: boolean
metadata?: string
length?: string
size?: number
```
> Rename `getOffset` to `getUpload`

- .eslintrc.json
- lib/Server.ts
- lib/configstores/MemoryConfigstore.ts
- lib/handlers/DeleteHandler.ts
- lib/handlers/GetHandler.ts
- lib/handlers/HeadHandler.ts
- lib/handlers/PatchHandler.ts
- lib/handlers/PostHandler.ts
- lib/models/File.ts
- lib/models/Upload.ts
- lib/stores/DataStore.ts
- lib/stores/FileStore.ts
- lib/stores/GCSDataStore.ts
- lib/stores/S3Store.ts
- test/Test-File.ts
- test/Test-FileStore.ts
- test/Test-GetHandler.ts
- test/Test-HeadHandler.ts
- test/Test-PatchHandler.ts
- test/Test-PostHandler.ts
- test/Test-Stores.shared.ts
- types/index.d.ts
- Rename `size` to `offset` and make the type non-optional
- Rename `upload_length` to `size`
- Create `sizeIsDeferred` getter
- Rename `upload_metadata` to `metadata`
- Should we rename `File` to `Upload` since we recently renamed the method that returns it to `getUpload`?
> Rename File model to Upload

- lib/stores/S3Store.ts
- tsconfig.json
Clean up in preparation for upcoming S3 store changes.
- Use `async`/`await`
- Improve types
- Simplify `write` and de-dupe network calls.
- Make `getUpload` consistent with other stores (no longer returning `parts`)
> Clean up `S3Store`

- lib/handlers/BaseHandler.ts
- test/Test-PostHandler.ts
- test/Test-Server.ts
- types/index.d.ts
Closes #256
Closes #134
Closes #59
Closes #170 
Closes #195
- Add new server option: `respectForwardedHeaders`.
- Respect `X-Forwarded-Host` and `X-forwarded-Proto` or `Forwarded` headers.
- Fix bug when `path` is set to root (`/`).
> Respect forwarded headers

- .github/workflows/ci.yml
- lib/models/StreamSplitter.ts
- lib/stores/S3Store.ts
- test/Test-StreamSplitter.ts
**Before**: uploading a 100 GB file with the default part size of 8 MB would fail the upload as it would be 12.5K parts, while the maximum allowed by S3 is 10K.
**After**: calculating the optimal part size which never exceeds the 10K limit.
Other changes:
- Modernize `StreamSplitter`
- Tiny refactors
> S3Store: calculate optimal part size

- lib/stores/GCSDataStore.ts
- lib/stores/S3Store.ts
Closes #300
Remove bucket existance check in S3 & GCS stores. Setting up a bucket is a prerequisite and we don't need to get fancy to check against that and waist time on network requests.
> Remove bucket existance check in S3 & GCS stores

- .eslintrc.json
- lib/Server.ts
- lib/constants.ts
- lib/handlers/DeleteHandler.ts
- lib/handlers/PatchHandler.ts
- lib/handlers/PostHandler.ts
- lib/stores/S3Store.ts
- test/Test-DeleteHandler.ts
- test/Test-PatchHandler.ts
- test/Test-PostHandler.ts
- test/Test-Server.ts
- types/index.d.ts
Closes #336 
Refs: #309 
- Remove `EVENT_ENDPOINT_CREATED`, `EVENT_FILE_CREATED`, `EVENT_UPLOAD_COMPLETE`, `EVENT_FILE_DELETED`
- Create `POST_CREATE`, `POST_RECEIVE`, `POST_FINISH`, `POST_TERMINATE`.
- Create blocking callbacks `onUploadCreate` and `onUploadFinish`. Error returned will be send back to the client.
Currently the error thrown in the callbacks expects an object `{body: 'some message', status_code: 500}`, which is consistent with the rest of our errors and has a fallback here:
https://github.com/tus/tus-node-server/blob/accb18b2f53d113ded2e176213f353ccc4de8f48/lib/Server.ts#L176-L184
This will be properly documented. But as I'm completely rewriting the readme and splitting up the packages, I'll do that when I get to it.
> Overhaul the events and hook callback system

- packages/s3-store/README.md
- packages/s3-store/index.ts
It's a bit odd to merge the tus store options with the S3 SDK client config options. The client config is also massive so it would pollute the types. Instead we now have a new options to pass to the S3 store: `s3ClientConfig`, which is directly passed to the SDK.
> @tus/s3-store: add `s3ClientConfig` option

- packages/server/src/validators/RequestValidator.ts
I met conditions when Server cannot handle request. The reasons is that RequestValidator missing validation functions for 'X-Forwarded-Host' and 'X-Forwarded-Proto' headers.
> @tus/server: fix header exception when using a load balancer

- packages/server/src/handlers/BaseHandler.ts
- packages/server/test/BaseHandler.test.ts
Properly encode `fileId` when composing URL and then decode when parsing. This allows user to use any naming function that is compatible with storage used.
> @tus/server: handle non-ASCII file IDs

- packages/s3-store/index.ts
> @tus/s3-store: fix uncaught exception when removing files

- test/e2e.test.ts
- test/package.json
- test/tsconfig.json
No type checking is performed on `e2e.test.ts` at build or test during CI or locally. 
This PR enables typescript type checking at build and test step and fixes compilation error that would happen with typescript 5.
> Fix e2e test typecheking

- packages/s3-store/index.ts
- packages/server/src/constants.ts
Hello,
I am proposing a change to the metadata field naming convention used in the AWS SDK S3 operations. Specifically, I recommend replacing underscores `_` with hyphens `-`.
In compliance with RFC 7230, HTTP headers should not contain underscores. However, I've noticed that the current implementation uses underscores in the metadata field names, which subsequently form part of the headers. This has the potential to lead to compatibility issues when interacting with services that strictly follow the standards. One such example is Nginx, which by default, ignores headers containing underscores.
When using the AWS SDK S3 to interact with S3-like services(minio) behind a proxy server (like Nginx), the service may return an error stating that "There were headers present in the request which …
> @tus/s3-store: replace Underscores with Hyphens in Metadata Field Names

- packages/server/src/models/StreamSplitter.ts
Related to https://github.com/tus/tus-node-server/issues/444 
If an error occurs during the write stream, we don't want to broadcast the chunkFinished event.
This should fix potential race conditions
> @tus/server: do not emit chunkFinished on error

- packages/s3-store/index.ts
- packages/s3-store/test.ts
Fixes #415
- if the current part is exactly the minimum part size, then that should also be allowed, not minimum + 1
- fix race condition in which the stream splitter is faster than uploading to S3, resulting the offset not being updated in time before the next chunk is handled.
> @tus/s3-store: fix min part size condition & offset race condition

- packages/s3-store/index.ts
- packages/s3-store/test.ts
This PR fixes incorrect `Upload-Offset` on HEAD request for uploads with incomplete part. 
First commit is the actual fix, second is non-mandatory refactor which makes `id` parameter having a consistent meaning for all functions in this class. Before this change `id` sometimes meant `<upload-id>`, but when working with incomplete parts it was expected to be `<upload-id>.part`.
Handling of suffix `.part` is moved into all functions that work directly with incomplete parts.
Note: this PR will conflict with #492 because of this second commit. I'll fix that when either is merged.
> @tus/s3-store: Fix offset calculation for uploads with incomplete part

- packages/s3-store/index.ts
- packages/s3-store/test.ts
Currently on every HEAD request entire incomplete part is downloaded to memory. 
This PR makes HEAD request to S3 to determine incomplete part size.
> @tus/s3-store: Don't download incomplete part on HEAD request

- packages/s3-store/index.ts
- packages/s3-store/test.ts
This PR improves transferring and prepending of incomplete parts. This was all done in-memory, but now this is changed to use streams. 
Incomplete parts are usually smaller than 5MB but chunk size can be up to 5GB in size. Reading all this to memory for concatenation is not a good idea.
> @tus/s3-store: Stream incomplete part instead of reading to memory

- demo/server.js
- packages/s3-store/README.md
- packages/s3-store/index.ts
- packages/s3-store/test.ts
This PR fixes #503.
When upload size is not known current calculated chunk size is `NaN` which causes request to be cached to disk without upper limit. Later it would be uploaded as part. If request was larger than 5GB (max size of single part) the upload would fail. 
This fix assumes maximum possible file size (5TiB) when calculating chunk size. Calculated chunk size for this size is `~524MiB`.
> @tus/s3-store: Fix invalid chunk size for uploads with deferred length

- packages/server/src/models/StreamSplitter.ts
- packages/server/test/StreamSplitter.test.ts
When handling incoming request, each buffer length is 64kb which `StreamSplitter` can handle without issues.
But in tests we might create buffers much larger than single part size, which might not be split as expected.
Works:
`const readStream = Readable.from(Buffer.alloc(expectedChunks * optimalChunkSize))`
Doesn't work:
`const readStream = Readable.from(`**`[`**`Buffer.alloc(expectedChunks * optimalChunkSize)`**`]`**`)`
> @tus/server: Split to multiple chunks on large incoming buffer

- packages/s3-store/index.ts
This PR fixes some issues with `retrieveParts` function.
First issue is how it determines when to fetch more parts. Before it was using `data.NextPartNumberMarker && Number(data.NextPartNumberMarker) > 0` to check if there are more parts to be fetch. This code made an assumption that final "page" will return "0" as `NextPartNumberMarker` but this is not specified in documentation and differs between S3 providers. Scaleway's S3 for example always return last part's number. Specification is clear on this that we should use `IsTruncated` propery.
Next issue is with sorting the parts. When completing multipart upload parts must be ordered in ascending order. In existing code sorting was done only when there less then 1000 parts (no additional "pages").
Another issue is with filtering. I'm not …
> @tus/s3-store: Fix incorrect part retreival procedure

- README.md
- packages/s3-store/README.md
- packages/s3-store/index.ts
- test/e2e.test.ts
- test/package.json
- test/s3.e2e.ts
Implements Expiration Extension for the S3 Store.
a new configuration is added on the S3Options to configure how long an upload URL will be valid for:
```ts
new S3Store({
expirationPeriodInMilliseconds: ((1000 * 60) * 60) * 24, // 24h
})
```
> @tus/s3-store: add expiration extension

- packages/server/src/handlers/DeleteHandler.ts
- packages/server/src/handlers/GetHandler.ts
- packages/server/src/handlers/HeadHandler.ts
- packages/server/src/handlers/PatchHandler.ts
- packages/server/src/handlers/PostHandler.ts
- packages/server/src/server.ts
- packages/server/src/types.ts
This PR makes the `onIncomingRequest` hook more useful by adding the `uploadId` as the 3rd parameter.
99% of cases you'd like to use this hook to perform authorization logic. However is always very common to allow check for permission specifically for certain upload-id.
For example:
- Can this user add chunks to this upload?
- Can this user view this asset?
By adding the upload-id we can implement custom logic on a per asset basis
> @tus/server: add upload id to `onIncomingRequest`

- packages/server/README.md
- packages/server/src/handlers/OptionsHandler.ts
- packages/server/src/types.ts
- packages/server/test/Server.test.ts
Currently, the list of allowed headers is hard-coded and there is no way to add custom headers if not overwriting the entire OptionHandler.
This PR allows to whitelisting of additional custom headers that can be passed on OPTION responses to pass CORS
```ts
new Server({
allowHeaders: ['X-Header-1', 'X-Header-2']
})
```
> @tus/server: allow passing custom headers

- packages/s3-store/index.ts
Tiny PR to allow setting the `CacheControl` header on the s3-store if the metadata field `cacheControl` is provided.
Similarly to how we handle `contentType`
> @tus/s3-store: allow passing cache-control parameter in metadata

- packages/s3-store/README.md
- packages/s3-store/index.ts
- test/s3.e2e.ts
This PR fixes #538 introduces a new option `useTags` which will allow disabling tagging objects for S3 providers who don't support them.
Tags will be now used only if the expiration extension is used.
> @s3/store: Allow disabling tagging on expiration extension

- packages/server/README.md
- packages/server/src/handlers/PostHandler.ts
- packages/server/src/types.ts
- packages/server/test/PostHandler.test.ts
This small PR simply allows error propagation in the namingFunction.
Currently, if an error is thrown from the `namingFunction` the error is swallowed and a 500 error code is returned.
This behavior is not ideal, in my use case I rely on the `metadata` in order to create a valid uploadID.
For this reason the `metadata` is validated in the naming function. If some of the fields don't pass the validation instead of returning a 400 status code, the application returns a non-ideal 500
> @tus/server: Metadata on namingFunction + propagate error

- packages/server/README.md
- packages/server/src/handlers/PostHandler.ts
- packages/server/src/types.ts
- packages/server/test/PostHandler.test.ts
Supporting an async namingFunction enables the check of existing files to ensure there are no collisions.
> @tus/server: add possibility to have an async namingFunction

- .github/workflows/ci.yml
- package.json
- packages/file-store/index.ts
- packages/file-store/test.ts
- packages/gcs-store/test.ts
- packages/s3-store/test.ts
- packages/server/test/Server.test.ts
- test/e2e.test.ts
- test/s3.e2e.ts
- test/stores.test.ts
- turbo.json
Attempt at running package tests in parallel as well as parallel runners between Node.js versions.
**Update**: getting rate limiting issues when running Node.js runners in parallel.
> Make tests concurrency safe and faster

- .changeset/wild-actors-leave.md
- packages/server/README.md
- packages/server/src/handlers/PostHandler.ts
- packages/server/src/types.ts
- packages/server/test/Server.test.ts
Closes #594 
Ref: #598 
Ref: #593
The types are atrocious because TS only understands type narrowing with `instanceof` but we can't use that because tests use mocked versions of `http.ServerResponse`.
> @tus/server: allow metadata changes in onUploadCreate

- .changeset/small-pandas-laugh.md
- packages/server/README.md
- packages/server/src/handlers/PatchHandler.ts
- packages/server/src/handlers/PostHandler.ts
- packages/server/src/types.ts
- packages/server/test/PostHandler.test.ts
- packages/server/test/Server.test.ts
Follow-up on #606. Changes based on #599.
> @tus/server: allow onUploadFinish hook to override response data

- .changeset/hungry-games-compete.md
- packages/file-store/index.ts
- packages/gcs-store/index.ts
- packages/s3-store/index.ts
- packages/server/test/DeleteHandler.test.ts
- packages/server/test/Server.test.ts
- packages/utils/src/models/DataStore.ts
- packages/utils/src/models/Upload.ts
- test/stores.test.ts
Closes #621 
Anything else we need to store in here?
cc @prolific @Acconut
> Add basic storage info to Upload model

- .changeset/smooth-kiwis-grow.md
- packages/server/README.md
- packages/server/src/handlers/BaseHandler.ts
- packages/server/src/types.ts
- packages/server/test/Server.test.ts
As soon as people want nested directories they have to implement `namingFunction`,`generateUrl`, and `getFileIdFromRequest`. 
Almost always, the last part of the path (after last `/`) is the ID. It's therefor a little awkward to let users repeat our internal code in `getFileIdFromRequest` again.
```js
const path = '/files'
const server = new Server({
path,
datastore: new FileStore({directory: './test/output'}),
namingFunction(req) {
const id = crypto.randomBytes(16).toString('hex')
const folder = getFolderForUser(req) // your custom logic
return `users/${folder}/${id}`
},
generateUrl(req, {proto, host, path, id}) {
id = Buffer.from(id, 'utf-8').toString('base64url')
return `${proto}://${host}${path}/${id}`
},
getFileIdFromRequest(req) {
const reExtractFileID = /([^/]+)\/?$/
const match = …
```
> @tus/server: add `lastPath` arg to `getFileIdFromRequest`

- .changeset/little-balloons-sort.md
- packages/server/src/handlers/GetHandler.ts
- packages/server/test/GetHandler.test.ts
The [tusd](https://github.com/tus/tusd) is the official implementation development in Go lang, and this adds `Content-Type` and `Content-Disposition` headers on response of `GetHandler`, this allows browser for:
- Recognize mime-type of file and render file inline or force download
- Suggest filename in save dialog
- [GetFile in tusd source code](https://github.com/tus/tusd/blob/0339037f874ccea5c6abdbfb424541f39f2db565/pkg/handler/unrouted_handler.go#L984)
> @tus/server: add Content-Type and Content-Disposition headers on GetHandler.send response

- .changeset/breezy-llamas-juggle.md
- .changeset/smooth-gifts-beam.md
- package-lock.json
- packages/s3-store/README.md
- packages/server/README.md
- packages/server/package.json
- packages/utils/package.json
- packages/utils/src/kvstores/IoRedisKvStore.ts
- packages/utils/src/kvstores/RedisKvStore.ts
- packages/utils/src/kvstores/index.ts
From [redis docs](https://redis.io/docs/latest/commands/keys/):
>Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using [SCAN](https://redis.io/docs/latest/commands/scan/) or [sets](https://redis.io/docs/latest/develop/data-types/sets/).
Added a new IoRedisKvStore. `SCAN` and raw command method signatures aren't compatible between node-redis and ioredis. Separate class is more maintainable and safer than making the redis client type an …
> Improved redis kv stores

- .changeset/plenty-actors-compare.md
- packages/s3-store/src/index.ts
- packages/s3-store/test/index.ts
Fixes #686 
Fixes #688 
Caused by a [regression](https://github.com/tus/tus-node-server/commit/227ae813e0d550f5b413af42920b8f7c47695d47#diff-fecfad9cf273825148c4be6b30379a6331608acd8b71f5acd9fc60c2286be034L365-R370)
This PR correctly increment the part number
> @tus/s3-store: fix part number increment

- .changeset/cyan-hornets-repair.md
- packages/s3-store/src/index.ts
Changes the `private` modifier in S3 store into `protected` so that they can be extended. I've also exported the `Options` type so that it can be used while extending.
> @tus/s3-store: Change private modifier into protected

- .changeset/calm-adults-roll.md
- packages/server/src/handlers/BaseHandler.ts
- packages/server/src/lockers/MemoryLocker.ts
- packages/server/src/server.ts
- packages/server/test/Locker.test.ts
- packages/server/test/PatchHandler.test.ts
- packages/server/test/utils.ts
- packages/utils/src/models/Locker.ts
This PR fixes #697 by always cancelling the context when the `req.on('close')` is emitted.
> The close event on the request (req) object is emitted when the underlying connection is terminated before the request is fully processed. This typically happens when the client abruptly disconnects, closes the browser, or cancels the request (e.g., a page refresh or navigation away).
Handled Cancellation scenarios:
- Client aborts the request (signal is propagated to the proxy stream and lockers)
- If the locker is trying to acquire a lock, it will stop since there is no more need
- Lock is acquired, the proxy stream is closed gracefully so that we can finishing uploading the remaining bytes in the buffer before releasing the lock
- Client completes the request correctly (without keep alive) the …
> fix: handling consistent cancellation across stream and locks

- .changeset/gold-adults-warn.md
- packages/s3-store/src/index.ts
- packages/s3-store/test/index.ts
> @tus/s3-store: fix zero byte files

- .changeset/proud-terms-swim.md
- packages/gcs-store/src/index.ts
> @tus/gcs-store: correctly pass content type

- .changeset/ten-buttons-suffer.md
- packages/s3-store/README.md
- packages/s3-store/src/index.ts
Closes #632
Ref: https://github.com/tus/tusd/issues/1137
> @tus/s3-store: add `minPartSize` option

- .changeset/silver-students-invent.md
- packages/server/src/lockers/MemoryLocker.ts
> @tus/server: don't use AbortSignal.any to fix memory leak

- .changeset/thin-keys-whisper.md
- packages/s3-store/README.md
I didn't update documentation in #712.
> @tus/s3-store: add missing docs for `maxMultipartParts`

- .changeset/weak-panthers-fold.md
- packages/azure-store/src/index.ts
- test/src/stores.test.ts
> @tus/azure-store: fix non-ASCII characters error on metadata

- .changeset/little-pets-unite.md
- package-lock.json
- packages/gcs-store/package.json
This is to split the breaking change out of #616 so that PR can land anything without needing a breaking change.
> @tus/gcs-store: require @google-cloud/storage ^7

- .changeset/happy-countries-ring.md
- packages/server/src/handlers/PatchHandler.ts
Resolves https://github.com/tus/tus-node-server/issues/751 by simply converting the type of "Upload-Offset" header value from number to string.
> @tus/server: make upload-offset a string

- .changeset/dull-fans-drop.md
- packages/server/src/handlers/BaseHandler.ts
- packages/server/src/handlers/PatchHandler.ts
- packages/server/src/handlers/PostHandler.ts
> @tus/server: fix promise rejection for stream conversion

- .changeset/tidy-items-fry.md
- packages/server/README.md
- packages/server/src/server.ts
- packages/server/src/test/Server.test.ts
- packages/server/src/types.ts
> @tus/server: introduce options.exposedHeaders

- .changeset/modern-birds-appear.md
- packages/server/src/server.ts
This PR fixes 2 regressions:
- Handle gracefully the request cancellation by aborting the context, which will allow the locks to be released immediately and available to be acquired by subsequent requests. Currently, this has been broken since the context was never cancelled when the request was aborted
- Force closing the connection when the request was aborted, to prevent the client from needing to send the whole body before realising that the upload was cancelled (potentially from another request acquiring the lock)
CC: @Murderlon
> @tus/server: handle request cancellation gracefully

- .changeset/nasty-drinks-itch.md
- packages/s3-store/src/index.ts
> @tus/s3-store: fix offset NaN when there are no parts
